### PR TITLE
Db connect remove capacity

### PR DESCRIPTION
**Pull request by ThorstenFroehlinghaus**
remove default value 40

### CODE REVIEW

**Review by hbruch — CHANGES_REQUESTED** [review]
Could you please reformat according to the linting suggestion?

And could you please add a short comment to the CHANGELOG?

**Comment by ThorstenFroehlinghaus** [comment]
I changed the formatting and added a Changelog comment.

**Comment by ThorstenFroehlinghaus** [comment]
sorry, wrong comment. i will change it

**Comment by ThorstenFroehlinghaus** [comment]
done

**Pull request merged**
